env:
  node: true
  es6: true
  jest: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
rules:
  consistent-return: 0
  import/extensions: 0
  semi:
    - error
    - never
  no-unused-vars:
    - warn
  no-console:
    - error
    - allow:
        - debug
        - info
        - warn
        - error
  no-underscore-dangle:
    - error
    - allow:
      - "_id"
